{{- if .Values.service.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "krewmuseum.serviceName" . }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "krewmuseum.labels" . | nindent 4 }}
  {{- if .Values.annotations -}}
  annotations:
    {{- include "krewmuseum.annotations" . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort)))) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if (and (eq .Values.service.type "LoadBalancer") .Values.service.sourceRanges) }}
  loadBalancerSourceRanges:
  {{- with .Values.service.sourceRanges }}
{{ toYaml . | indent 2 }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- end }}
  ports:
  - port: {{ .Values.service.externalPort }}
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{.Values.service.nodePort}}
    {{- else }}
    targetPort: {{ .Values.service.targetPort }}
    {{- end }}
    protocol: {{ .Values.service.portProtocol}}
    name: {{ .Values.service.portName }}
  selector: 
    {{- include "krewmuseum.labels" . | nindent 4}}
{{- end -}}