{{- if and .Values.persistence.enabled ( eq .Values.persistence.type "statefulset" ) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "krewmuseum.name" . }}
  {{- if .Values.namespaceOverride }}
  namespace: {{ .Values.namespaceOverride }}
  {{- end }}
  labels:
    {{- include "krewmuseum.labels" . | nindent 4 }}
  {{- if .Values.annotations -}}
  annotations:
    {{- include "krewmuseum.annotations" . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "krewmuseum.labels" . | nindent 6 }}
  serviceName: {{ include "krewmuseum.name" . }}-svc
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        {{- include "krewmuseum.labels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      {{ with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.gracePeriod }}
      containers:
      - name: {{ include "krewmuseum.name" . }}
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- include "krewmuseum.envs" . | nindent 8 }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10}}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10}}
        {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- range .Values.persistence.mounts }}
        - name:  {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
        {{ end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
      - name: {{ .name }}
      {{- end -}}
      {{- end }}
        
  volumeClaimTemplates:
    {{- include "krewmuseum.volumeClaimTemplate" . | nindent 4 }}
{{- end -}}